version: '3'
services:
  app:
    build: ./
    ports:
    - 8080:8080
    - 9090:9090
    networks:
      app:
        ipv4_address: 172.16.238.10
  proxy:
    build:
     context: .
     dockerfile: ./proxy-Dockerfile
    ports:
    - 19090:19090 
    networks:
      app:
        ipv4_address: 172.16.238.11
networks:
  app:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"